# ===============================================================================
# DATASET CONVERTER — Used by dataset_converter.py
# ===============================================================================
dataset_converter:
  verbose: false # Enable verbose output for dataset converter
  low_memory: true # The low memory parameter for reading the files.
  input_file_formats: ["arff", "csv", "parquet", "txt"] # Supported input formats: arff,csv,parquet,txt. Defaults to all
  output_file_formats: ["arff", "csv", "parquet", "txt"] # Supported output formats: arff,csv,parquet,txt. Defaults to all
  output_directory: "Converted" # Default output directory for converted datasets; use "in-place" to save converted files in the same directory as the input file
  datasets: # Dictionary containing dataset paths
    CAIDA-2007:
    - "./Datasets/CAIDA 2007/"
    CICDDoS2019-Dataset:
      - "./Datasets/CICDDoS2019/01-12/"
      - "./Datasets/CICDDoS2019/03-11/"
    CIC-IDS2017-Dataset:
      - "./Datasets/CICIDS2017/TrafficLabelling/"
    ISCX-IDS-2012:
      - "./Datasets/ISCX IDS 2012/data/CSV/" 
    KDD-Dataset:
      - "./Datasets/KDD-Dataset/"
    LATAM-DDoS-IoT:
      - "./Datasets/LATAM DDoS IoT/"
    UGR-16:
      - "./Datasets/UGR-16/uniq/"
    UNSW-NB15-Dataset:
      - "./Datasets/UNSW-NB15-Dataset/"
  ignore_dirs:
    - "Classifiers"
    - "Classifiers_Hyperparameters"
    - "Converted"
    - "Data_Separability"
    - "Dataset_Description"
    - "Feature_Analysis"
    - "Results" # Directory names to ignore during discovery
  ignore_files: ["results", "summary"] # Filename substrings to ignore
